require "active_resource"
require "galaxy/version"
require "galaxy/timeify"
require "galaxy/base"

require "galaxy/address"
require "galaxy/coupon"
require "galaxy/credit_card"
require "galaxy/category"
require "galaxy/category_preference"
require "galaxy/saved_deal"
require "galaxy/card_link"
require "galaxy/location"
require "galaxy/deal"
require "galaxy/email"
require "galaxy/merchant"
require "galaxy/purchase"
require "galaxy/region"
require "galaxy/subscription"
require "galaxy/user"
require "galaxy/reset_token"
require "galaxy/merchants/deal_summary"
require "galaxy/match"
require "galaxy/promotion"

require "activeresource/validations"
