require "active_resource"
require "galaxy/version"
require "galaxy/base"
require "galaxy/coupon"
require "galaxy/credit_card"
require "galaxy/deal"
require "galaxy/email"
require "galaxy/merchant"
require "galaxy/purchase"
require "galaxy/region"
require "galaxy/subscription"
require "galaxy/user"
require "galaxy/reset_token"

require "activeresource/validations"
